### ISSUE TITLE
If delegation amount is below mininum the error shows "[object Object]" as the needed amount.

### ISSUE THREAD

**Issue by muksihs** [steemscript/steemconnect#338] opened 2018-09-30 03:28 UTC
![image](https://user-images.githubusercontent.com/32560971/46252984-61f17d00-c43f-11e8-9440-6e4eedc4355f.png)

**Comment by bonustrack** [comment] 2019-04-20 11:44
Duplicate of #301

**Closed by bonustrack** 2019-04-20 11:44 UTC
