### ISSUE TITLE
Redelegation errored out with "power descrease is not enough" Min update value shows as [object Object].

### ISSUE THREAD

**Issue by muksihs** [steemscript/steemconnect#340] opened 2018-09-30 15:58 UTC
![image](https://user-images.githubusercontent.com/32560971/46259479-0ad3c280-c4a8-11e8-971c-55f64f854766.png)

**Comment by bonustrack** [comment] 2019-04-20 11:44
Duplicate of #301

**Closed by bonustrack** 2019-04-20 11:44 UTC
